// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcp.proto

package com.project.grpc;

/**
 * Protobuf type {@code ConnectionRequest}
 */
public  final class ConnectionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ConnectionRequest)
    ConnectionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConnectionRequest.newBuilder() to construct.
  private ConnectionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConnectionRequest() {
    msgXml_ = "";
    msgPb_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConnectionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConnectionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            msgXml_ = bs;
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            msgPb_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.project.grpc.GrpcProto.internal_static_ConnectionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.project.grpc.GrpcProto.internal_static_ConnectionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.project.grpc.ConnectionRequest.class, com.project.grpc.ConnectionRequest.Builder.class);
  }

  private int bitField0_;
  public static final int MSG_XML_FIELD_NUMBER = 1;
  private volatile java.lang.Object msgXml_;
  /**
   * <pre>
   *Talvez posssa mudar para optional
   * </pre>
   *
   * <code>optional string msg_xml = 1;</code>
   */
  public boolean hasMsgXml() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *Talvez posssa mudar para optional
   * </pre>
   *
   * <code>optional string msg_xml = 1;</code>
   */
  public java.lang.String getMsgXml() {
    java.lang.Object ref = msgXml_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        msgXml_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *Talvez posssa mudar para optional
   * </pre>
   *
   * <code>optional string msg_xml = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMsgXmlBytes() {
    java.lang.Object ref = msgXml_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgXml_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_PB_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString msgPb_;
  /**
   * <pre>
   *Para mandar as cenas dos protobuffers atraves de um array de bytes
   * </pre>
   *
   * <code>optional bytes msg_pb = 2;</code>
   */
  public boolean hasMsgPb() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   *Para mandar as cenas dos protobuffers atraves de um array de bytes
   * </pre>
   *
   * <code>optional bytes msg_pb = 2;</code>
   */
  public com.google.protobuf.ByteString getMsgPb() {
    return msgPb_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgXml_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, msgPb_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgXml_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, msgPb_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.project.grpc.ConnectionRequest)) {
      return super.equals(obj);
    }
    com.project.grpc.ConnectionRequest other = (com.project.grpc.ConnectionRequest) obj;

    if (hasMsgXml() != other.hasMsgXml()) return false;
    if (hasMsgXml()) {
      if (!getMsgXml()
          .equals(other.getMsgXml())) return false;
    }
    if (hasMsgPb() != other.hasMsgPb()) return false;
    if (hasMsgPb()) {
      if (!getMsgPb()
          .equals(other.getMsgPb())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMsgXml()) {
      hash = (37 * hash) + MSG_XML_FIELD_NUMBER;
      hash = (53 * hash) + getMsgXml().hashCode();
    }
    if (hasMsgPb()) {
      hash = (37 * hash) + MSG_PB_FIELD_NUMBER;
      hash = (53 * hash) + getMsgPb().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.project.grpc.ConnectionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.project.grpc.ConnectionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.project.grpc.ConnectionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.project.grpc.ConnectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.project.grpc.ConnectionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ConnectionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ConnectionRequest)
      com.project.grpc.ConnectionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.grpc.GrpcProto.internal_static_ConnectionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.grpc.GrpcProto.internal_static_ConnectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.grpc.ConnectionRequest.class, com.project.grpc.ConnectionRequest.Builder.class);
    }

    // Construct using com.project.grpc.ConnectionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgXml_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      msgPb_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.project.grpc.GrpcProto.internal_static_ConnectionRequest_descriptor;
    }

    @java.lang.Override
    public com.project.grpc.ConnectionRequest getDefaultInstanceForType() {
      return com.project.grpc.ConnectionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.project.grpc.ConnectionRequest build() {
      com.project.grpc.ConnectionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.project.grpc.ConnectionRequest buildPartial() {
      com.project.grpc.ConnectionRequest result = new com.project.grpc.ConnectionRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.msgXml_ = msgXml_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.msgPb_ = msgPb_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.project.grpc.ConnectionRequest) {
        return mergeFrom((com.project.grpc.ConnectionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.project.grpc.ConnectionRequest other) {
      if (other == com.project.grpc.ConnectionRequest.getDefaultInstance()) return this;
      if (other.hasMsgXml()) {
        bitField0_ |= 0x00000001;
        msgXml_ = other.msgXml_;
        onChanged();
      }
      if (other.hasMsgPb()) {
        setMsgPb(other.getMsgPb());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.project.grpc.ConnectionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.project.grpc.ConnectionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object msgXml_ = "";
    /**
     * <pre>
     *Talvez posssa mudar para optional
     * </pre>
     *
     * <code>optional string msg_xml = 1;</code>
     */
    public boolean hasMsgXml() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *Talvez posssa mudar para optional
     * </pre>
     *
     * <code>optional string msg_xml = 1;</code>
     */
    public java.lang.String getMsgXml() {
      java.lang.Object ref = msgXml_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgXml_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Talvez posssa mudar para optional
     * </pre>
     *
     * <code>optional string msg_xml = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgXmlBytes() {
      java.lang.Object ref = msgXml_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgXml_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Talvez posssa mudar para optional
     * </pre>
     *
     * <code>optional string msg_xml = 1;</code>
     */
    public Builder setMsgXml(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      msgXml_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Talvez posssa mudar para optional
     * </pre>
     *
     * <code>optional string msg_xml = 1;</code>
     */
    public Builder clearMsgXml() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msgXml_ = getDefaultInstance().getMsgXml();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Talvez posssa mudar para optional
     * </pre>
     *
     * <code>optional string msg_xml = 1;</code>
     */
    public Builder setMsgXmlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      msgXml_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString msgPb_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *Para mandar as cenas dos protobuffers atraves de um array de bytes
     * </pre>
     *
     * <code>optional bytes msg_pb = 2;</code>
     */
    public boolean hasMsgPb() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *Para mandar as cenas dos protobuffers atraves de um array de bytes
     * </pre>
     *
     * <code>optional bytes msg_pb = 2;</code>
     */
    public com.google.protobuf.ByteString getMsgPb() {
      return msgPb_;
    }
    /**
     * <pre>
     *Para mandar as cenas dos protobuffers atraves de um array de bytes
     * </pre>
     *
     * <code>optional bytes msg_pb = 2;</code>
     */
    public Builder setMsgPb(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      msgPb_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Para mandar as cenas dos protobuffers atraves de um array de bytes
     * </pre>
     *
     * <code>optional bytes msg_pb = 2;</code>
     */
    public Builder clearMsgPb() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msgPb_ = getDefaultInstance().getMsgPb();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ConnectionRequest)
  }

  // @@protoc_insertion_point(class_scope:ConnectionRequest)
  private static final com.project.grpc.ConnectionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.project.grpc.ConnectionRequest();
  }

  public static com.project.grpc.ConnectionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ConnectionRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConnectionRequest>() {
    @java.lang.Override
    public ConnectionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConnectionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConnectionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConnectionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.project.grpc.ConnectionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

